In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Ordinal and Label encoding
We use label encoding for target categorical variable & ordinal encoding for ordinal features.
And for Nominal data we use One hot encoding

In [2]:
customer = pd.read_csv("E:\Data Science\Machine Learning\data\customer.csv")
customer.head(10)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Anwoy\AppData\Local\Temp\ipykernel_6096\1047983227.py:1: SyntaxWarning: invalid escape sequence '\D'
  customer = pd.read_csv("E:\Data Science\Machine Learning\data\customer.csv")

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes
6   18    Male     Good    School        No
7   60  Female     Poor    School       Yes
8   65  Female  Average        UG        No
9   74    Male     Good        UG       Yes

In [3]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train,y_test = train_test_split(customer.iloc[:, 2:4], customer.iloc[:, -1], test_size= 0.15)

In [4]:
X,y = customer.iloc[:, 2:4], customer.iloc[:, -1]

In [5]:
for i in X.columns:
    print(f"unique category {X[i].unique()}")

unique category ['Average' 'Poor' 'Good']
unique category ['School' 'UG' 'PG']

In [6]:
from sklearn.preprocessing import OrdinalEncoder

ode = OrdinalEncoder(categories= [['Poor', 'Average', "Good"], ["School", 'UG', 'PG']])

X = ode.fit_transform(X)

In [7]:
ode.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)

In [9]:
y

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

### One hot encoding

In [10]:
cars = pd.read_csv("E:\Data Science\Machine Learning\data\cars.csv")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Anwoy\AppData\Local\Temp\ipykernel_6096\1393840986.py:1: SyntaxWarning: invalid escape sequence '\D'
  cars = pd.read_csv("E:\Data Science\Machine Learning\data\cars.csv")

In [11]:
cars

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [12]:
for i in cars.columns:
    if (cars[i].dtype) == 'object':
        print(f"unique category {cars[i].unique()}\n")

unique category ['Maruti' 'Skoda' 'Honda' 'Hyundai' 'Toyota' 'Ford' 'Renault' 'Mahindra'
 'Tata' 'Chevrolet' 'Fiat' 'Datsun' 'Jeep' 'Mercedes-Benz' 'Mitsubishi'
 'Audi' 'Volkswagen' 'BMW' 'Nissan' 'Lexus' 'Jaguar' 'Land' 'MG' 'Volvo'
 'Daewoo' 'Kia' 'Force' 'Ambassador' 'Ashok' 'Isuzu' 'Opel' 'Peugeot']

unique category ['Diesel' 'Petrol' 'LPG' 'CNG']

unique category ['First Owner' 'Second Owner' 'Third Owner' 'Fourth & Above Owner'
 'Test Drive Car']

### 1. One Hot encoding using pandas

In [13]:
pd.get_dummies(cars,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

#### 2. n-1 one hot encoding

In [14]:
pd.get_dummies(cars,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [15]:
from sklearn.preprocessing import OneHotEncoder

ode = OneHotEncoder(sparse_output=False,dtype=np.int32)

ode.fit_transform(cars[["fuel","owner"]])

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int32)

In [16]:
from sklearn.preprocessing import OneHotEncoder

ode = OneHotEncoder(drop ='first', sparse_output=False,dtype=np.int32)

ode.fit_transform(cars[["fuel","owner"]]).shape

(8128, 7)

In [17]:
from sklearn.preprocessing import OneHotEncoder

ode = OneHotEncoder(sparse_output=False,dtype=np.int32)

ode.fit_transform(cars).shape

(8128, 1639)

### One hot encoding with top categories
- when there are huge number of categories we can replace uncommon types with 'other'/'uncommon' etc.

In [19]:
cars.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [23]:
counts = cars['brand'].value_counts()

In [27]:
threshold = 100

repl = counts[counts <= threshold].index

In [33]:
pd.get_dummies(cars['brand'].replace(repl, 'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False